server {
    listen 80;
    server_name localhost;

    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        # PHP-FPM runs on the host, so it must receive the host filesystem path
        # instead of nginx's container path (/var/www/html).
        fastcgi_param SCRIPT_FILENAME /home/bmafazi/code/personal/laravel-starter-kit/public$fastcgi_script_name;
        fastcgi_pass host.docker.internal:9000;
    }
}
